# Multi Matrix Clock In Distributed Operating Systems

In [1]:
import numpy as np

In [2]:
# A function to show the current status for each process

def show_values():
    for i in di.items():
        pro, val=i
        print(pro)
        for j in val:
            print(j)
        print()
        

In [3]:
# A function to show the current status for global matrix

def show_global():
    print("\nGlobal Matrix")
    for j in globall:
        print(j)

In [4]:
#A function to update the values for each process and global matrix

def update(source, destination, arr):
    
    ''' Source holds the Sender's Name
        Destination holds the Receiver's Name
        arr holds the sender's own position's 1D array only'''
    
    if destination=='X':
        print("\nEvent is not successfull\nEvent Aborted")
        print("The Global Matrix is not updated & it holds it's previous value")
    else:
        if source==destination:                        # For Self internal event
            ss=des=process[source]                     
        else:
            ss=process[source]                         # For Send & Receive event
            des=process[destination]
                
        for i in range(len(di[destination])):
            for j in range(len(di[destination][i])):
                if (i==des and j==des):                # Self vector self position update
                    di[destination][i][j]=max(di[destination][i][j], arr[j])+1
                elif(i==des):                          # Self vector other positions update
                    di[destination][i][j]=arr[j] 
                elif(i==ss):                           # Self Matrix Sender position update
                    di[destination][i][j]=max(di[destination][i][j], arr[j])
                else:                                  # Self Matrix all other postion update
                    di[destination][i][j]=di[destination][i][j]
                    
                                        
        for j in range(len(di[destination][des])):
            globall[des][j]=max(di[destination][des][j], globall[des][j])
            
        print("\nThe Global Matrix is Updated")
            

Driver Code

In [5]:
#Multi Matrix Clock Implementation


n=int(input("Enter number of processes: "))  # Taking number of processes as input
process={}
ch=True                                     # If the user wants to perform more event
for i in range(1,n+1):                      # Creating a list of all the processes
    process[f'P{i}']=(i-1)
    
# print(process)

di={}
for i in process:                           # Creating a matrix of size n*n for each process 
    di[i]=np.array([[0]*n]*n)
    
globall=np.array([[0]*n]*n)                 # Creating a global matrix for all processes

# print(di)


while (ch):
    print("\n\n1. Internal Event\n2. Send Event\n3. Exit")
    op=input("Enter your choice: ")
    if(op.isdigit()):
        op=int(op)
        if(op==1):
            sender=input("Enter the Source name(p1/p2/...): ").upper()
            update(sender,sender,np.array(di[sender][process[sender]]))
            show_values()
            show_global()
        elif(op==2):
            sender=input("\nEnter the Source Process name(p1/p2/...): ").upper()
            print("\nEnter Destination process as 'x' to denote a cancelled event")
            receiver=input("\nEnter the Destination Process name(p1/p2/...): ").upper()
            update(sender,receiver,np.array(di[sender][process[sender]]))
            show_values()
            show_global()
        elif(op==3):
            break
        else:
            print("\nOops!...Invalid Choice\nEnter Valid Choice")
            continue
    else:
        print("\nInvalid choice\nChoice should be an integer number\nTry Again!")
        continue

Enter number of processes: 3


1. Internal Event
2. Send Event
3. Exit
Enter your choice: 1
Enter the Source name(p1/p2/...): p1

The Global Matrix is Updated
P1
[1 0 0]
[0 0 0]
[0 0 0]

P2
[0 0 0]
[0 0 0]
[0 0 0]

P3
[0 0 0]
[0 0 0]
[0 0 0]


Global Matrix
[1 0 0]
[0 0 0]
[0 0 0]


1. Internal Event
2. Send Event
3. Exit
Enter your choice: 1
Enter the Source name(p1/p2/...): p3

The Global Matrix is Updated
P1
[1 0 0]
[0 0 0]
[0 0 0]

P2
[0 0 0]
[0 0 0]
[0 0 0]

P3
[0 0 0]
[0 0 0]
[0 0 1]


Global Matrix
[1 0 0]
[0 0 0]
[0 0 1]


1. Internal Event
2. Send Event
3. Exit
Enter your choice: 2

Enter the Source Process name(p1/p2/...): p1

Enter Destination process as 'x' to denote a cancelled event

Enter the Destination Process name(p1/p2/...): p2

The Global Matrix is Updated
P1
[1 0 0]
[0 0 0]
[0 0 0]

P2
[1 0 0]
[1 1 0]
[0 0 0]

P3
[0 0 0]
[0 0 0]
[0 0 1]


Global Matrix
[1 0 0]
[1 1 0]
[0 0 1]


1. Internal Event
2. Send Event
3. Exit
Enter your choice: 2

Enter the Source Process n